### ISSUE TITLE
Events Dashboard for Spaces

### ISSUE THREAD

**Issue by brianking** [mozilla/community-spaces#18]
## Objective Goal:

To show statistics on events in community spaces (primarily dev events) to determine the health of the developer engagement program and the spaces in general

R: @couci 
A: @brianking
C: @yofiesetiawan 
I:
## Tasks & To Dos Related to This Project:
- Tracking events spreadsheet: https://docs.google.com/a/mozilla.com/spreadsheets/d/1h8nsKT00FVrRLUu1-2hpM-p0GD3eHztYB5AqdKm0suw/edit?usp=sharing
## Sub-Goal Success:
- [x] Update spreadsheet with latest numbers - end May ( @rara79 @bobchao @bobreyes ) 
- [x] Determine event types for dropdown ( @brianking ) 
- [x] Design advice ( @yofiesetiawan ) 
- [x] Build dashboard ( @couci ) 
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by brianking** [comment]
Initial data to show:
- Total number of events all spaces
- Total numbers of events per space
- Attendees all 
- Attendees per space
- Total number of new (+ per space)
- Total number of returning  (+ per space)
- Chart of attendees in time for all and for per space
- Pie with events with % of each space

In all the visualisation, we need to surface up stats about dev events in particular (# of, attendees at, ....)

Start date April 1

**Comment by yofiesetiawan** [comment]
Hi Brian, 
Should we also count the statistic number of people who came, not for events? Like looking around or cowork?

**Comment by brianking** [comment]
@yofiesetiawan feel free to keep track of that but it is not something we will be monitoring right now.

**Comment by couci** [comment]
Hey @yofiesetiawan could you help with a design on how the dashboard would look like? We are going to build it on spreadsheets for now but I'm looking for ideas on how to display the info properly.

**Comment by yofiesetiawan** [comment]
Hi @couci of course, please let me know once we have fix data that we want to present. I will create an infographic for that... Per month?

**Comment by couci** [comment]
in that case we have to wait for @rara79 @bobchao @bobreyes to update the spreadsheet.
Yes I was thinking on counting data on a per month bases and show the progress into time

**Comment by bobreyes** [comment]
@couci Apr and May 2016 data for MozSpaceMNL updated already. Thanks!

**Comment by rara79** [comment]
done for May 2016 ^.^

**Comment by irvin** [comment]
Taipei updated, thanks

**Comment by yofiesetiawan** [comment]
![space-report-may-2016](https://cloud.githubusercontent.com/assets/2810823/16518455/0fdfa08c-3fad-11e6-8b7e-0aa2efc15352.jpg)

Please review..

**Comment by brianking** [comment]
@yofiesetiawan looks fantastic! Not sure if G Sheets can make something so pretty but we can try. Or, after we have the charts done, we can make them look prettier somewhere else if needed.

@couci is this enough for you to go with, or do need mockups for all the data points we want to show as mentioned in comment 1?

**Comment by couci** [comment]
thanks a lot @yofiesetiawan !
@brianking this is monthly only, do you a dashboard that will show progress over time too?
Also would you like tabs with different spaces or 1 to rule them all?

**Comment by brianking** [comment]
Definitely we need to show data over time. On a quick glance, it doesn't seem like there is any data we need to show per month. However, if you come across something you think should, let us know.

Let's have 4 tabs:
- 1 for each space.
- 1 global, that shows aggregate data and global trends from all spaces.

**Comment by yofiesetiawan** [comment]
Hi,
Please check on the spreadsheet, tab "statistics", i've made a clear summary table of reports, unfortunately, i'm not sure how to translate that (properly) to dynamic charts on Google Spreadsheet. If anyone could help, that would be great..

**Comment by brianking** [comment]
Yofie, thanks. Konstantina can help with pulling those numbers in automatically.

As for mockups, you can drop then in here:
https://docs.google.com/a/mozilla.com/document/d/1HVgcG7f_NgiKL2RjLG3Zbvne8Mw-vC9j_GHhmz_z3CQ/edit?usp=sharing

**Comment by irvin** [comment]
we have a data resource spreadsheet* so I think we can come back to work on this issue, 
https://docs.google.com/spreadsheets/d/1h8nsKT00FVrRLUu1-2hpM-p0GD3eHztYB5AqdKm0suw/edit#gid=1946775411

1. what data do we missing on "dashboard" tab? 
2. do we have new update dashboard design?
3. pull data from google spreadsheet and rendering into web page

**Comment by irvin** [comment]
@yofiesetiawan can you come up with a new design that includes devrel events num. and devrel visitors?

**Comment by brianking** [comment]
Done (see #27).

https://datastudio.google.com/open/0B1QBPp2E8AIKQVdpZTBFc1R2SjA

Thanks @kelimuttu !
